# GitHub Action to deploy WebPerformance Report Static Site on production
name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV_SERVER }}
          username: ${{ secrets.SSH_USERNAME_DEV_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV_SERVER }}
          script: |
            # Navigate to the project directory
            cd /var/www/vhosts/webperformancereport.com/httpdocs/

            # Pull the latest code
            git status
            git add .
            git stash
            git pull https://${{ secrets.SSH_GIT_TOKEN }}@github.com/WebPerformanceReport/wpr-static-site.git main

